### ISSUE TITLE
Opacity of the basemap not set correctly

### ISSUE THREAD

**Issue by gedicb** [conterra/mapapps-basemap-slider#2]
When using the dn_basemapslider bundle, it has been noticed that the opacity setting is not quite correct when selecting the background map directly. It happens that the previous background map still shows through (to see on the right side of the screenshot). We used map.apps in version 4.11.1.

Screenshot:
![Fehler_basemapslider](https://user-images.githubusercontent.com/60434030/171107771-e047a1fd-2fad-4f02-bf7d-4fac7d66d3bb.JPG)

**Comment by sholtkamp** [comment]
Cannot reproduce with map.apps 4.17.0 and bundle version 1.2.5.
Please reopen this issue if the errors persist on your end.
